language: php

services:
  - mysql

env:
  global:
    - WP_DB_USER=wp
    - WP_DB_PASS=password
    - WP_DB_NAME=wp_tests
    - WP_VERSION=latest-stable

matrix:
  fast_finish: true
  include:
    - &lint
      php: 7.3
      script:
        - npm run lint
      env: JOB_NAME=lint
    - &test
      php: 7.3
      script:
        - mysql -u root -e "GRANT ALL PRIVILEGES ON ${WP_DB_NAME}.* TO ${WP_DB_USER} IDENTIFIED BY '${WP_DB_PASS}';"
        - mysql -u root -e "CREATE DATABASE ${WP_DB_NAME};"
        - npm run test-only
      env: JOB_NAME=test
    - <<: *test
      env: JOB_NAME=test WP_VERSION=master
    - <<: *test
      env: JOB_NAME=test ADDITIONAL_COMPOSER_OPTIONS="--prefer-lowest"
    - <<: *test
      env: JOB_NAME=coverage
    - <<: *test
      php: 7.2
    - <<: *test
      php: 7.1
    - <<: *test
      php: 7.0
    - <<: *test
      php: 5.6
      env: JOB_NAME=test ADDITIONAL_COMPOSER_OPTIONS="--prefer-lowest"
    - <<: *test
      php: 5.5
      env: JOB_NAME=test ADDITIONAL_COMPOSER_OPTIONS="--prefer-lowest"
    - <<: *test
      php: 5.4
      env: JOB_NAME=test ADDITIONAL_COMPOSER_OPTIONS="--prefer-lowest"
    - <<: *test
      php: 5.4
      env: JOB_NAME=test ADDITIONAL_COMPOSER_OPTIONS="--prefer-lowest"

cache:
  directories:
    - $HOME/.npm
    - node_modules
    - $HOME/.composer/cache
    - vendor

before_install:
  - if [[ $JOB_NAME != "coverage" ]]; then phpenv config-rm xdebug.ini || true; fi
  - travis_retry npm install -g npm@latest
  - node -v
  - npm -v
  - travis_retry composer self-update
  - php -v
  - composer --version

install:
  - travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest $ADDITIONAL_COMPOSER_OPTIONS;
  - if [[ $WP_VERSION != "latest-stable" ]]; then
    cd vendor/wordpress/wordpress;
    git checkout $WP_VERSION;
    cd ../../../;
    fi
  - travis_retry npm ci

after_success:
  - if [[ $JOB_NAME == "coverage" ]]; then
    travis_retry wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar;
    chmod +x php-coveralls.phar;
    travis_retry php vendor/bin/php-coveralls -x coverage/phpunit/logs/clover.xml -o ./coverage/coverage.json -v;
    fi
